plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

configurations.all {
    exclude group: "com.thingclips.smart",
            module: "thingsmart-modularCampAnno"
}

android {

    namespace 'com.example.geysermen'

    compileSdk 35

    defaultConfig {
        applicationId "com.example.geysermen"

        minSdk 24
        targetSdk 35

        versionCode 1
        versionName "1.0"

    }

    buildFeatures {
        prefab true
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }

        resources {
            excludes += [
                    "META-INF/**"
            ]
        }
    }

    packagingOptions {
        pickFirst "**/libc++_shared.so"
        pickFirst "**/*.so"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }
}

dependencies {

    implementation fileTree(
            dir: "libs",
            include: ["*.aar"]
    )

    implementation 'com.alibaba:fastjson:1.1.67.android'

    implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.14.9'

    implementation 'com.thingclips.smart:thingsmart:7.5.1'

    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'

    implementation 'com.google.android.material:material:1.10.0'

    implementation 'androidx.activity:activity-ktx:1.7.2'

    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    implementation 'com.thingclips.smart:thingsmart:6.7.0'

    // ADD THIS
    //implementation 'com.android.ndk.thirdparty:libc++:1.0.0'
}